# Generated by Django 3.2 on 2022-02-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Endurance', 'Endurance'), ('Technique', 'Technique')], default='Strength', max_length=30)),
                ('length', models.CharField(choices=[('Short < 25mins', 'Short < 25mins'), ('Medium 30-45mins', 'Medium 30-45mins'), ('Long > 45mins', 'Long > 45mins')], default='Short < 25mins', max_length=30)),
                ('participants', models.CharField(choices=[('Single', 'Single'), ('Duo', 'Duo'), ('Trio', 'Trio')], default='Single', max_length=30)),
                ('equipment', models.CharField(choices=[('Dumbbell', 'Dumbbell'), ('Barbell', 'Barbell'), ('Kettlebell', 'Kettlebell'), ('Assault bike', 'Assault bike'), ('Plyobox', 'Plyobox'), ('Rig', 'Rig'), ('Wallball', 'Wallball'), ('Jumprope', 'Jumprope'), ('Rope', 'Rope'), ('Rower', 'Rower'), ('SkiErg', 'SkiErg')], default='Dumbbell', max_length=30)),
                ('author', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='workout_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
