# Generated by Django 3.2 on 2022-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wod', '0002_auto_20220202_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Endurance', 'Endurance'), ('Technique', 'Technique')], default='Strength', max_length=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='equipment',
            field=models.CharField(choices=[('Dumbbell', 'Dumbbell'), ('Barbell', 'Barbell'), ('Kettlebell', 'Kettlebell'), ('Assault bike', 'Assault bike'), ('Plyobox', 'Plyobox'), ('Rig', 'Rig'), ('Wallball', 'Wallball'), ('Jumprope', 'Jumprope'), ('Rope', 'Rope'), ('Rower', 'Rower'), ('SkiErg', 'SkiErg')], default='Dumbbell', max_length=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='length',
            field=models.CharField(choices=[('Short < 25mins', 'Short < 25mins'), ('Medium 30-45mins', 'Medium 30-45mins'), ('Long > 45mins', 'Long > 45mins')], default='Short < 25mins', max_length=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='participants',
            field=models.CharField(choices=[('Single', 'Single'), ('Duo', 'Duo'), ('Trio', 'Trio')], default='Single', max_length=30),
        ),
    ]
